// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KafkaConsumer.Model
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Test : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Test"",""namespace"":""KafkaConsumer.Model"",""fields"":[{""name"":""_id"",""type"":""string""},{""name"":""desc"",""type"":""string""},{""name"":""subscription"",""default"":null,""type"":[""null"",""string""]},{""name"":""apps"",""default"":null,""type"":[""null"",{""type"":""array"",""items"":""string""}]}]}");
		private string @__id;
		private string _desc;
		private string _subscription;
		private IList<System.String> _apps;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Test._SCHEMA;
			}
		}
		public string _id
		{
			get
			{
				return this.@__id;
			}
			set
			{
				this.@__id = value;
			}
		}
		public string desc
		{
			get
			{
				return this._desc;
			}
			set
			{
				this._desc = value;
			}
		}
		public string subscription
		{
			get
			{
				return this._subscription;
			}
			set
			{
				this._subscription = value;
			}
		}
		public IList<System.String> apps
		{
			get
			{
				return this._apps;
			}
			set
			{
				this._apps = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._id;
			case 1: return this.desc;
			case 2: return this.subscription;
			case 3: return this.apps;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._id = (System.String)fieldValue; break;
			case 1: this.desc = (System.String)fieldValue; break;
			case 2: this.subscription = (System.String)fieldValue; break;
			case 3: this.apps = (IList<System.String>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
